# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  install:
    desc: Install dependencies for release build
    cmd: conan install --build missing
    sources:
      - conanfile.txt
    generates:
      - build/Release/generators/**
      - CMakeUserPresets.json

  install-debug:
    desc: Install dependencies for debug build
    cmd: conan install --build missing --settings build_type=Debug
    sources:
      - conanfile.txt
    generates:
      - build/Debug/generators/**
      - CMakeUserPresets.json

  prepare-build:
    desc: Set up the build system for a release build
    deps: [install]
    cmd: source build/Release/generators/conanbuild.sh \
            && cmake --preset conan-release
    sources:
      - conanfile.txt
      - CMakeUserPresets.json
    generates:
      - build/Release/**
      - exclude: build/Release/generators/**
      - exclude: build/Release/aoc25
      - exclude: build/Release/aoc25test

  prepare-build-debug:
    desc: Set up the build system for a debug build
    deps: [install-debug]
    cmd: source build/Debug/generators/conanbuild.sh \
            && cmake --preset conan-debug
    sources:
      - conanfile.txt
      - CMakeUserPresets.json
    generates:
      - build/Debug/**
      - exclude: build/Debug/generators/**
      - exclude: build/Debug/aoc25
      - exclude: build/Debug/aoc25test

  build:
    desc: Create a release build of the app
    deps: [prepare-build]
    cmd: source build/Release/generators/conanbuild.sh \
            && cmake --build --preset conan-release \
            && cmake --install build/Release --prefix .
    sources:
      - conanfile.txt
      - CMakeLists.txt
      - CMakeUserPresets.json
      - src/**/*.h
      - src/**/*.c
      - test/**/*.h
      - test/**/*.c
    generates:
      - bin/Release/**

  build-debug:
    desc: Create a debug build of the app
    deps: [prepare-build-debug]
    cmd: source build/Debug/generators/conanbuild.sh \
            && cmake --build --preset conan-debug \
            && cmake --install build/Debug --prefix .
    sources:
      - conanfile.txt
      - CMakeLists.txt
      - CMakeUserPresets.json
      - src/**/*.h
      - src/**/*.c
      - test/**/*.h
      - test/**/*.c
    generates:
      - bin/Debug/**

  test:
    desc: Test the app
    deps: [build-debug]
    cmd: ./bin/Debug/aoc25Test

  run:
    desc: Run the release build of the app
    deps: [build]
    cmd: ./bin/Release/aoc25

  run-debug:
    desc: Run the debug build of the app
    deps: [build-debug]
    cmd: ./bin/Debug/aoc25

  cleanup:
    desc: Remove all build related files
    prompt: This will delete all build related files. Are you sure?
    cmds:
      - rm -rf bin
      - rm -rf build
      - rm -f CMakeUserPresets.json
