# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  install:
    desc: Install dependencies and set up build system
    cmds:
      - conan install --output-folder build --build missing
      - source build/conanbuild.sh \
          && cmake -B build -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
    sources:
      - conanfile.txt
    generates:
      - build/**
      - CMakeUserPresets.json
      - exclude: build/CMakeFiles/aoc25.dir/src/**
      - exclude: build/CMakeFiles/aoc25Test.dir/src/**

  build:
    desc: Build the app
    deps: [install]
    cmd: source build/conanbuild.sh \
      && cmake --build build
    sources:
      - conanfile.txt
      - CMakeLists.txt
      - src/**/*.h
      - src/**/*.c
      - test/**/*.h
      - test/**/*.c
    generates:
      - bin/aoc25
      - bin/aoc25Test

  test:
    desc: Test the app
    deps: [build]
    cmd: ./bin/aoc25Test

  run:
    desc: Run the app
    deps: [build]
    cmd: ./bin/aoc25

  cleanup:
    desc: Remove all build related files
    prompt: This will delete all build related files. Are you sure?
    cmds:
      - rm -rf bin
      - rm -rf build
      - rm -f CMakeUserPresets.json
