# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  install:
    desc: Install dependencies and set up build system
    cmd: conan install --output-folder build/conan
    sources:
      - conanfile.txt
    generates:
      - build/conan/**
      - CMakeUserPresets.json

  prepare-build:
    desc: Prepare the build system
    deps: [install]
    cmd: source build/conan/conanbuild.sh \
      && cmake -B build/cmake -DCMAKE_TOOLCHAIN_FILE=build/conan/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
    sources:
      - CMakeLists.txt
    generates:
      - build/cmake/**
      - exclude: build/cmake/CMakeFiles/aoc25.dir/src/**

  build:
    desc: Build the app
    deps: [prepare-build]
    cmd: source build/conan/conanbuild.sh \
      && cmake --build build/cmake
    sources:
      - src/**/*.h
      - src/**/*.c
    generates:
      - bin/aoc25

  run:
    desc: Run the app
    deps: [build]
    cmds:
      - ./bin/aoc25
